### PR TITLE
Adds "Some" to prevents build error on Rust 1.50.0

### PR DESCRIPTION
**Pull request by sergiosvieira**

### CODE REVIEW

**Comment by puiterwijk** [comment]
Note that this is not an error with Rust 1.50, this would be an error if we were linking against `tss-esapi-4.0.10-alpha.2`, but in `alpha.1`, this is not yet an `Option`.

**Comment by puiterwijk** [comment]
Note the difference between [alpha.1](https://docs.rs/tss-esapi/4.0.10-alpha.1/tss_esapi/struct.Context.html#method.create_key) and [alpha.2](https://docs.rs/tss-esapi/4.0.10-alpha.2/tss_esapi/struct.Context.html#method.create_key): the `creation_pcrs` argument changed from `PcrSelectionList` to `Option<PcrSelectionList>`.

**Comment by puiterwijk** [comment]
Given the differences between alpha 1 and 2, I am relatively sure this will need more changes, so I'll go look at rebasing it.

**Comment by sergiosvieira** [comment]
Ok

**Comment by puiterwijk** [comment]
@sergiosvieira Sorry for being a bit short. Thank you very much for your patch!

**Pull request closed without merging**
